### ISSUE TITLE
是否可以在llama.cpp中体验该项目的优化功能

### ISSUE THREAD

**Issue by CsBoBoNice** [microsoft/T-MAC#13]
您好，

很高兴在readme上看到以下动态

```
08/14/2024 🚀: The T-MAC GEMM (N>1) kernels are now integrated into llama.cpp to accelerate prefill.
```

我在llama.cpp项目中未找到与该项目相关的的更新说明与pr(可能是我没看仔细)

请问是否可以在llama.cpp中体验该项目的优化功能

期待您的回复！

**Comment by kaleid-liner** [comment]
The feature is implemented in [this commit](https://github.com/kaleid-liner/llama.cpp/commit/6049c4cf20acc1e4c679b6ffa01b175f5cbd12d7). We haven't issued any pull request to the mainstream. Follow README.md to use our own fork.
