### ISSUE TITLE
llama-2-7b 4bit convert fail issue(2bit is ok)

### ISSUE THREAD

**Issue by AndreaChiChengdu** [microsoft/T-MAC#31]
![Screenshot from 2024-08-28 20-06-17](https://github.com/user-attachments/assets/dc2c4db3-d6d0-4dda-a71f-46a63887482e)

hi there, I am using the pre-build ini for gguf 2bit/4bit llama2-7b model convert on my ubuntu x86 pc,
deploy/tuned/aarch64-llama-2-7b-2bit/kcfg.ini pass and gen gguf model
deploy/tuned/aarch64-llama-2-7b-4bit/kcfg.ini fail as the photo above
please check this issue
thanks

logs:
python convert-hf-to-gguf-t-mac.py ./Llama-2-7b-hf/ --outtype i4 --outfile ./llama-2-7b-4bit.gguf --kcfg ../../deploy/tuned/aarch64-llama-2-7b-4bit/kcfg.ini
INFO:hf-to-gguf:Loading model: Llama-2-7b-hf
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:gguf: context length = 4096
INFO:hf-to-gguf:gguf: embedding length = 4096
INFO:hf-to-gguf:gguf: feed forward length = 11008
INFO:hf-to-gguf:gguf: head count = 32
INFO:hf-to-gguf:gguf: key-value head count = 32
INFO:hf-to-gguf:gguf: rms norm epsilon = 1e-05
INFO:hf-to-gguf:gguf: file type = 32
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Setting special token type bos to 1
INFO:gguf.vocab:Setting special token type eos to 2
INFO:gguf.vocab:Setting special token type unk to 0
INFO:gguf.vocab:Setting add_bos_token to True
INFO:gguf.vocab:Setting add_eos_token to False
INFO:hf-to-gguf:Exporting model to 'llama-2-7b-4bit.gguf'
INFO:hf-to-gguf:gguf: loading model part 'model-00001-of-00002.safetensors'
INFO:hf-to-gguf:gguf: loading model part 'model-00002-of-00002.safetensors'
INFO:hf-to-gguf:gguf: loading model part 'model-00001-of-00002.safetensors'
INFO:hf-to-gguf:token_embd.weight, n_dims = 2, torch.float16 --> F16
INFO:hf-to-gguf:blk.0.attn_norm.weight, n_dims = 1, torch.float16 --> F32
Traceback (most recent call last):
File "convert-hf-to-gguf-t-mac.py", line 3421, in
main()
File "convert-hf-to-gguf-t-mac.py", line 3413, in main
model_instance.write()
File "convert-hf-to-gguf-t-mac.py", line 277, in write
self.write_tensors()
File "convert-hf-to-gguf-t-mac.py", line 1783, in write_tensors
data = preprocess_for_t_mac(w, scales, zeros, bits=bits)
File "convert-hf-to-gguf-t-mac.py", line 3192, in preprocess_for_t_mac
raise KeyError("GEMM of shape ({}, {}) is not found in {}. Please compile the kernels using T-MAC first.".format(M, K, args.kcfg))
KeyError: 'GEMM of shape (4096, 11008) is not found in ../../deploy/tuned/aarch64-llama-2-7b-4bit/kcfg.ini. Please compile the kernels using T-MAC first.'

**Comment by kaleid-liner** [comment]
It seems the model in your folder `./Llama-2-7b-hf/` is a 2-bit GPTQ model but you are trying to convert it to 4-bit with 4-bit `kcfg.ini`. You need to download the corresponding 4-bit GPTQ model.

**Comment by AndreaChiChengdu** [comment]
> It seems the model in your folder `./Llama-2-7b-hf/` is a 2-bit GPTQ model but you are trying to convert it to 4-bit with 4-bit `kcfg.ini`. You need to download the corresponding 4-bit GPTQ model.

Thanks for the prompt response, but llama-2-7b-hf is original llama2 7b fp model from hugging face meta repo cli download but not 2bit gptq model

**Comment by kaleid-liner** [comment]
@AndreaChiChengdu In this case, the script assumes the model is a 2-bit quantized model in BitDistiller format. You should use a GPTQ model. There are a lot of llama 4-bit GPTQ models at HuggingFace, such as TheBloke or EfficientQAT.
