### ISSUE TITLE
where is t-mac-envs.sh

### ISSUE THREAD

**Issue by idreamerhx** [microsoft/T-MAC#37]
where to find t-mac-envs.sh

**Comment by kaleid-liner** [comment]
Seems a duplicate of #26. However, I still can't reproduce this issue on my Jetson AGX Orin or Ubuntu WSL. Can you provide the full log of `pip install -e . -v`, Python version, OS version and pip version to help me to reproduce?

**Comment by kaleid-liner** [comment]
And refer to https://github.com/microsoft/T-MAC/issues/26#issuecomment-2324397827 as a workaround.

**Comment by idreamerhx** [comment]
Hi, I completely build this project on x86 docker. use miniconda3.9, ubuntu22.04 and really a lot of modifiations and retries...  
the ./build/t-mac-envs.sh was generated. 

i run   python setup.py install    in TMAC root dir sereval times.

**Comment by kaleid-liner** [comment]
> Hi, I completely build this project on x86 docker. use miniconda3.9, ubuntu22.04 and really a lot of modifiations and retries...  
> the ./build/t-mac-envs.sh was generated. 
> 
> i run   python setup.py install    in TMAC root dir sereval times. 

Great! It would be helpful if you can spare your time to issue a pull request or describe the solution.
