### ISSUE TITLE
Compile TVM failed 

### ISSUE THREAD

**Issue by velonica0** [microsoft/T-MAC#42]
Hi, I want to run T-MAC, but it fails during the process of compiling TVM. The compilation of T-MAC shows success. The following is my log. How should I modify it?

/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libzstd.a(zstd_common.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: failed to set dynamic section sizes: bad value
  collect2: error: ld returned 1 exit status
  make[2]: *** [CMakeFiles/tvm.dir/build.make:1998：libtvm.so] 错误 1
  make[1]: *** [CMakeFiles/Makefile2:175：CMakeFiles/tvm.dir/all] 错误 2
  make: *** [Makefile:136：all] 错误 2
  /tmp/pip-build-env-gd1jabs3/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py:289: SetuptoolsDeprecationWarning: Customization incompatible with editable install
  !!

          ********************************************************************************
                          Traceback (most recent call last):
            File "<string>", line 118, in build_tvm
            File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

          The above exception was the direct cause of the following exception:

          Traceback (most recent call last):
            File "/tmp/pip-build-env-gd1jabs3/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 295, in _safely_run
              return self.run_command(cmd_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-gd1jabs3/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
              self.distribution.run_command(command)
            File "/tmp/pip-build-env-gd1jabs3/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
              super().run_command(command)
            File "/tmp/pip-build-env-gd1jabs3/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
              cmd_obj.run()
            File "<string>", line 151, in run
            File "<string>", line 120, in build_tvm
          RuntimeError: Failed to build TVM

                          If you are seeing this warning it is very likely that a setuptools
                          plugin or customization overrides the `build_py` command, without
                          taking into consideration how editable installs run build steps
                          starting from setuptools v64.0.0.

                          Plugin authors and developers relying on custom build steps are
                          encouraged to update their `build_py` implementation considering the
                          information about editable installs in
                          https://setuptools.pypa.io/en/latest/userguide/extension.html.

                          For the time being `setuptools` will silence this error and ignore
                          the faulty command, but this behaviour will change in future versions.

          ********************************************************************************

  !!

**Comment by kaleid-liner** [comment]
Can you provide me more info to reproduce, such as your OS, python version, and are you using venv or conda?

**Comment by velonica0** [comment]
> Can you provide me more info to reproduce, such as your OS, python version, and are you using venv or conda?

Sorry, I didn't notice your message.

Kernel: 6.6.0-1-generic x86_64

openKylin2.0

venv: Python 3.11

**Comment by velonica0** [comment]
@khayamgondal @kaleid-liner 
I encountered the same problem on Ubuntu24, but I used TVM's GitHub repository to compile and ran T-MAC successfully.

**Comment by sunj0104** [comment]
so happy to see that answer, May I ask which branch of TVM's GitHub repository?  36b9535?

**Comment by velonica0** [comment]
> so happy to see that answer, May I ask which branch of TVM's GitHub repository? 36b9535?

37555713a023802ad7926addb37a5a8d43fd991f
The latest branch I was using at the time
