### ISSUE TITLE
Compile kernels failed,RuntimeError: Compilation error: /tmp/tmpxinqgwfx/input0.cc:20:10: fatal error: 'type_traits' file not found

### ISSUE THREAD

**Issue by xiangzhangpang** [microsoft/T-MAC#47]
earlier,i got a error
OSError: /home/orangepi/miniconda3/envs/T-MAC/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/orangepi/T-MAC/3rdparty/tvm/build/libtvm.so)
and i fixed by the following
(T-MAC) orangepi@node1:~/T-MAC/deploy$ ln -s /usr/lib/aarch64-linux-gnu/libstdc++.so.6 /home/orangepi/miniconda3/envs/T-MAC/lib/libstdc++.so.6
now i gat a new error,
![1](https://github.com/user-attachments/assets/6bed5069-ba31-4cc4-98ef-558a8f1f9c05)
ubuntu22.04
Kernel:6.1.43-rockchip-rk3588
python3.8
can someone help me

**Comment by kaleid-liner** [comment]
It seems libstdc++ is missing on your machine. Install it through `apt install ibstdc++-12-dev`.

**Comment by kaleid-liner** [comment]
Great. I will close this issue as completed.
