### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes during GEMV kernel profiling with TMAC

### ISSUE THREAD

**Issue by KoalaYuFeng** [microsoft/T-MAC#55]
Hi,

Firstly, excellent work! It has been incredibly inspiring. I'm currently performing a performance breakdown of the GEMV kernel using TMAC, focusing on the percentage of precompute operations in each GEMV stage. However, I encountered the following error when running the command `python profile.py -k preprocessor` with `MKNs = [4096, 4096, 2]`: ValueError: operands could not be broadcast together with shapes (2,256,64) (2,64).
#### Questions:
1. **Root Cause of the Error**:
   - I would like to understand the root cause of this broadcasting issue. It seems there is a shape mismatch between the tensors involved in the operation. Could you provide insights into why this might be occurring and how to resolve it?
2. **Understanding Multi-Batch Lookup Table Construction**:
   - In my understanding, for a multi-batch setting, the CPU constructs a separate Lookup Table (LUT) for each batch, which should imply that the time consumption is linear with `N`. I also noticed in the code that `N` is within a loop during GEMV execution. Could you please confirm if my understanding is correct?

Thank you for your time and for the fantastic work!

**Comment by kaleid-liner** [comment]
1. I haven't encountered this issue. Let me try and debug it.
2. Yes. The time consumption of LUT construction is linear with `N`. However, the time is negligible. `N` is within a loop during GEMV execution.

**Comment by KoalaYuFeng** [comment]
> 1. I haven't encountered this issue. Let me try and debug it.
> 2. Yes. The time consumption of LUT construction is linear with `N`. However, the time is negligible. `N` is within a loop during GEMV execution.

Thanks for your reply. For point 2, as you say "However, the time is negligible", could you please give a more detailed explanation? Based on my profiling, the pre-compute stage accounts for about 10% when processing [1,4096] * [4096, 4096] matrix-vector multiplication. Thanks again.
