### ISSUE TITLE
when i change kfator lager than 16, then ca not get a right result

### ISSUE THREAD

**Issue by qw1319** [microsoft/T-MAC#57]
hi when i add tune search space:  add some config kfactor(32, 64, 128);
then tune result selcect the kfactor=32 result.  But when i run this kernel, can not get a right answer.
Is this right（the red block）？
![Image](https://github.com/user-attachments/assets/5a65db80-c062-4fb9-a624-2b34405858e3)

**Comment by qw1319** [comment]
> I haven't tested kfactor=32 kernels in llama.cpp e2e inference. However, it seems the result is correct indicated by `python tools/profile.py -k qgemm_lut` and `python tools/profile.py -k preprocessor` given `kfactor=32, MKNs = [[4096, 4096, 1]], act_group_size=64, group_size=128`.

I mean can not get right answer(generated token is error), not performance

**Comment by kaleid-liner** [comment]
> > I haven't tested kfactor=32 kernels in llama.cpp e2e inference. However, it seems the result is correct indicated by `python tools/profile.py -k qgemm_lut` and `python tools/profile.py -k preprocessor` given `kfactor=32, MKNs = [[4096, 4096, 1]], act_group_size=64, group_size=128`.
> 
> I mean can not get right answer(generated token is error), not performance

`verify=True` in `tools/profile.py` will verify the results against `_reference` (implemented using numpy). If there isn't assert error,  it indicates the computation obtains correct results.
