### ISSUE TITLE
Why is there no difference in the E2E performance of T-MAC and llama.cpp on arm machine?

### ISSUE THREAD

**Issue by ppp-max** [microsoft/T-MAC#60]
I used a ARM machine to test the end-to-end output, but the performance does not match the results mentioned in the paper.  The tested data of llama.cpp and T-MAC is nearly same. I've posted the measured data below.
![Image](https://github.com/user-attachments/assets/d3488cb1-b9a0-47e9-b3dc-43c74e580405)
![Image](https://github.com/user-attachments/assets/97c26285-e91b-4688-89dd-719cdf28731e)
And  the frequency of this machine is 2.5 GHz, the bandwidth of  this machine 2.6 G/s per core.

**Comment by kevinoldching** [comment]
Are there any errors when you used cmake to build?
