### ISSUE TITLE
lastest tmac version run error

### ISSUE THREAD

**Issue by qw1319** [microsoft/T-MAC#63]
when i run tmac (commit id:649432908776b3a867e96419e098f827d0f8c1ee)
run cmd `python tools/run_pipeline.py -o /new_tmac/Llama-2-7b-EfficientQAT-w4g128-GPTQ/ -m llama-2-7b-4bit`
then i meet error

`INFO:hf-to-gguf:Loading model: Llama-2-7b-EfficientQAT-w4g128-GPTQ
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:gguf: loading model part 'model.safetensors'
INFO:hf-to-gguf:output.weight,               torch.float16 --> F16, shape = {4096, 32001}
INFO:hf-to-gguf:token_embd.weight,           torch.float16 --> F16, shape = {4096, 32001}
INFO:hf-to-gguf:blk.0.attn_norm.weight,      torch.float16 --> F32, shape = {4096}
Traceback (most recent call last):
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 4547, in <module>
    main()
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 4541, in main
    model_instance.write()
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 531, in write
    self.prepare_tensors()
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 1751, in prepare_tensors
    super().prepare_tensors()
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 368, in prepare_tensors
    for new_name, data_torch in (self._modify_tensors(data_torch, name, bid)):
  File "/new_tmac/T-MAC/3rdparty/llama.cpp/convert_hf_to_gguf.py", line 323, in _modify_tensors
    data_torch = torch.from_numpy(preprocess_for_t_mac(self.kcfg_file, w, scales, zeros, bits=bits))
  File "/new_tmac/T-MAC/python/t_mac/model_utils.py", line 255, in preprocess_for_t_mac
    return np.concatenate([w.flatten(), scales.astype(np.float32).view(np.uint8).flatten()])
ValueError: To change to a dtype of a different size, the array must be C-contiguous
`

**Comment by kaleid-liner** [comment]
Can you check if the fix works?

**Comment by qw1319** [comment]
> Can you check if the fix works?

Thx, it wroks，  But I get more worse performance. 
`llama_perf_sampler_print:    sampling time =      25.49 ms /   152 runs   (    0.17 ms per token,  5962.42 tokens per second)
llama_perf_context_print:        load time =    9241.41 ms
llama_perf_context_print: prompt eval time =   33642.30 ms /    24 tokens ( 1401.76 ms per token,     0.71 tokens per second)
llama_perf_context_print:        eval time =  199067.48 ms /   127 runs   ( 1567.46 ms per token,     0.64 tokens per second)
llama_perf_context_print:       total time =  232777.26 ms /   151 tokens`

**Comment by qw1319** [comment]
> Can you check if the fix works?

it works thx
