### ISSUE TITLE
咨询关于LUT的构建疑惑

### ISSUE THREAD

**Issue by matrix97317** [microsoft/T-MAC#77]
![Image](https://github.com/user-attachments/assets/70204a0e-15f0-46c6-a12f-b079c19c2366)
论文中，对于LUT 构建，这里为啥要减去 A，不应该是直接将其放置为0么，对于每一个激活有两个状态 0、1.  可以答疑解惑下么。

**Comment by QingtaoLi1** [comment]
@matrix97317 Please refer to https://github.com/microsoft/T-MAC/issues/73.
